package com.msp360.at.wizards.steps;

public enum ScheduleTypeMonthly {

    TYPE_MONTHLY("Monthly"),

    TYPE_MONTHLY_OCCURRENCE_DAY_OF_MONTH("Day Of Month"),
    TYPE_MONTHLY_OCCURRENCE_FIRST("First"),
    TYPE_MONTHLY_OCCURRENCE_SECOND("Second"),
    TYPE_MONTHLY_OCCURRENCE_THIRD("Third"),
    TYPE_MONTHLY_OCCURRENCE_FOURTH("Fourth"),
    TYPE_MONTHLY_OCCURRENCE_LAST("Last"),
    TYPE_MONTHLY_OCCURRENCE_PENULTIMATE("Penultimate"),

    TYPE_MONTHLY_MONDAY("Monday"),
    TYPE_MONTHLY_TUESDAY("Tuesday"),
    TYPE_MONTHLY_WEDNESDAY("Wednesday"),
    TYPE_MONTHLY_THURSDAY("Thursday"),
    TYPE_MONTHLY_FRIDAY("Friday"),
    TYPE_MONTHLY_SATURDAY("Saturday"),
    TYPE_MONTHLY_SUNDAY("Sunday"),

    TYPE_MONTHLY_DAY_OF_MONTH_1("1"),
    TYPE_MONTHLY_DAY_OF_MONTH_2("2"),
    TYPE_MONTHLY_DAY_OF_MONTH_3("3"),
    TYPE_MONTHLY_DAY_OF_MONTH_4("4"),
    TYPE_MONTHLY_DAY_OF_MONTH_5("5"),
    TYPE_MONTHLY_DAY_OF_MONTH_6("6"),
    TYPE_MONTHLY_DAY_OF_MONTH_7("7"),
    TYPE_MONTHLY_DAY_OF_MONTH_8("8"),
    TYPE_MONTHLY_DAY_OF_MONTH_9("9"),
    TYPE_MONTHLY_DAY_OF_MONTH_10("10"),
    TYPE_MONTHLY_DAY_OF_MONTH_11("11"),
    TYPE_MONTHLY_DAY_OF_MONTH_12("12"),
    TYPE_MONTHLY_DAY_OF_MONTH_13("13"),
    TYPE_MONTHLY_DAY_OF_MONTH_14("14"),
    TYPE_MONTHLY_DAY_OF_MONTH_15("15"),
    TYPE_MONTHLY_DAY_OF_MONTH_16("16"),
    TYPE_MONTHLY_DAY_OF_MONTH_17("17"),
    TYPE_MONTHLY_DAY_OF_MONTH_18("18"),
    TYPE_MONTHLY_DAY_OF_MONTH_19("19"),
    TYPE_MONTHLY_DAY_OF_MONTH_20("20"),
    TYPE_MONTHLY_DAY_OF_MONTH_21("21"),
    TYPE_MONTHLY_DAY_OF_MONTH_22("22"),
    TYPE_MONTHLY_DAY_OF_MONTH_23("23"),
    TYPE_MONTHLY_DAY_OF_MONTH_24("24"),
    TYPE_MONTHLY_DAY_OF_MONTH_25("25"),
    TYPE_MONTHLY_DAY_OF_MONTH_26("26"),
    TYPE_MONTHLY_DAY_OF_MONTH_27("27"),
    TYPE_MONTHLY_DAY_OF_MONTH_28("28"),
    TYPE_MONTHLY_DAY_OF_MONTH_29("29"),
    TYPE_MONTHLY_DAY_OF_MONTH_30("30"),
    TYPE_MONTHLY_DAY_OF_MONTH_31("31");


    private final String type;

    ScheduleTypeMonthly(String classType) {
        this.type = classType;
    }

    public String toString() {
        return type;

    }
}
